CREATE TABLE [dbo].[LeagueConfig] (
    [Id] INT IDENTITY(1,1) PRIMARY KEY,
    [countPoints] BIT NOT NULL,
    [allowSanma] BIT DEFAULT 0 NOT NULL,
    [startingPoints] FLOAT,
    [uma3p1] FLOAT,
    [uma3p2] FLOAT,
    [uma3p3] FLOAT,
    [uma4p1] FLOAT,
    [uma4p2] FLOAT,
    [uma4p3] FLOAT,
    [uma4p4] FLOAT,
    [oka] FLOAT,
    [penaltyLast] FLOAT,
    [penaltyChombo] FLOAT,
    [useEloSystem] BIT NOT NULL,
    [initialElo] FLOAT,
    [minElo] FLOAT,
    [baseEloChangeDampening] FLOAT,
    [eloChangeStartRatio] FLOAT,
    [eloChangeEndRatio] FLOAT,
    [trialPeriodDuration] INT,
    [startDate] DATETIME   NOT NULL DEFAULT (SYSDATETIME() - interval '12 months'),
    [endDate] DATETIME   NOT NULL DEFAULT (SYSDATETIME() + interval '12 months'),
);