CREATE TABLE [dbo].[Game] (
    [Id] INT IDENTITY(1,1) PRIMARY KEY,
    [gameId]  NCHAR (100) NULL,
    [platform]  NCHAR (100) NOT NULL,
    [user1Id]     NCHAR (20) NOT NULL,
    [user1Score]  INT          ,
    [user1Signed] BIT          DEFAULT ((0)) NOT NULL,
    [user2Id]     NCHAR (20) NOT NULL,
    [user2Score]  INT          ,
    [user2Signed] BIT          DEFAULT ((0)) NOT NULL,
    [user3Id]     NCHAR (20) NOT NULL,
    [user3Score]  INT          ,
    [user3Signed] BIT          DEFAULT ((0)) NOT NULL,
    [user4Id]     NCHAR (20) NOT NULL,
    [user4Score]  INT          ,
    [user4Signed] BIT          DEFAULT ((0)) NOT NULL,
    [timestamp]   DATETIME   NOT NULL DEFAULT SYSDATETIME(),
    [serverId] NCHAR (20) NOT NULL,
    FOREIGN KEY ([user1Id]) REFERENCES [dbo].[User] ([Id]),
    FOREIGN KEY ([user2Id]) REFERENCES [dbo].[User] ([Id]),
    FOREIGN KEY ([user3Id]) REFERENCES [dbo].[User] ([Id]),
    FOREIGN KEY ([user4Id]) REFERENCES [dbo].[User] ([Id]),
    FOREIGN KEY ([serverId]) REFERENCES [dbo].[Server] ([Id])
);